# https://github.com/arendst/Sonoff-Tasmota/wiki/4CH-Wifi-Socket-with-USB-Charger-SA-P402A-(TYWE2S)

substitutions:
  device_name: powerstrip2
  friendly_name: powerstrip2

esphome:
  name: $device_name
  platform: ESP8266
  board: esp8285

wifi:
  ssid: !secret wifi_ssid
  password: !secret wifi_password
  
logger:

web_server:
  port: 80

api:
  password: !secret hass_api

ota:
  password: !secret hass_api
  
switch:

- platform: gpio
  pin: GPIO3
  inverted: no
  #restore_mode: ALWAYS_OFF
  id: 'ledi'
  name:  $friendly_name ledi

- platform: gpio
  pin: GPIO12
  id: 'relay1'
  name:  $friendly_name relay1

- platform: gpio
  pin: GPIO14
  id: 'relay2'
  name:  $friendly_name relay2

- platform: gpio
  pin: GPIO4
  id: 'relay3'
  name:  $friendly_name relay3

- platform: gpio
  pin: GPIO13
  id: 'relay4'
  name:  $friendly_name relay4
  
- platform: gpio
  pin: GPIO5
  id: 'relay5'
  name:  $friendly_name relay5
  
- platform: template
  name: Switch All
  id: switch_all
  optimistic: true
  turn_on_action:
  - switch.turn_on: relay1
  - switch.turn_on: relay2
  - switch.turn_on: relay3
  - switch.turn_on: relay4
  - switch.turn_on: relay5
  turn_off_action:
  - switch.turn_off: relay1
  - switch.turn_off: relay2
  - switch.turn_off: relay3
  - switch.turn_off: relay4
  - switch.turn_off: relay5

binary_sensor:
- platform: gpio
  pin:
    number: GPIO1
    inverted: yes
  id: button
  name: Button
  on_press:
    then:
    - switch.toggle: switch_all
